on:
  schedule:
  - cron: "0 4 * * *"
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build-maps:
    name: "Build maps"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Prepare environment
      run: |
        cd garmin
        ./prepare.sh

    - name: Build maps
      run: |
        cd garmin
        wget -nv https://download.geofabrik.de/europe/lithuania-latest.osm.pbf
        ./build-lt.sh lithuania-latest.osm.pbf stranger

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OSM Garmin Lithuania maps
        path: garmin/out
        if-no-files-found: error
        overwrite: true
